version: '3.7'
services:
  redis:
      image: "redis:alpine"
      hostname: redis
      ports:
        - "6379:6379"

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: project
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb_container
    depends_on:
      - mongodb_container

  mysql_container:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'database_development'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'NewUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'NewUser'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3333:3306'
    expose:
      # Opens port 3306 on the container
      - '3333'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - mysql_container
    environment:
      PMA_HOST: mysql_container
      PMA_USER: root
      PMA_PASSWORD: "password"
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8888:80"

volumes:
  mongodb_data_container:
  mysql-db: